# Generated by Django 3.0.8 on 2020-08-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('education', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=150)),
                ('passing_year', models.CharField(max_length=10)),
                ('about', models.CharField(max_length=500)),
                ('notes', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
