# Generated by Django 3.0.8 on 2020-08-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0002_auto_20200822_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='notes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
    ]
